### ISSUE TITLE
Keep null values in serialized body when indexing

### ISSUE THREAD

**Issue by gignonje** [elastic/enterprise-search-php#15]
Hi,

We're considering switching from deprecated `elastic/app-search-php` to `elastic/enterprise-search-php`.
However, I found a strange behavioural choice that I don't understand and you might be able to help me figure it out.

When indexing documents, we must use an `IndexDocuments` request, requiring as second argument an array of `Document`.
It works well, except with `nullable` fields. If the field as no value, we can't index this field as it is automatically removed from request at serialization time: https://github.com/elastic/enterprise-search-php/blob/master/src/Request/Request.php#L90.

We can't bypass that as serializers are not configurable, and body in `IndexDocuments` could not accept anything other than an array.

Why would you remove prevent nullable fields from indexing ? 

Let's imagine that you have order data to index, that has multiple fields, including `creationDate` and `deliveryDate`. 
`deliveryDate` is nullable when the order is not yet delivered.
As you can't index `deliveryDate` field, it is not present in the document response, and you could not filter results having null deliveryDate, right ?

Is it a bad practice to index nullable fields having null value ? If not, would it be possible to allow indexing of null values ?

Thank you.

**Comment by ezimuel** [comment]
Hi @gignonje we removed the `null` value in request object because we are using typed properties and we need to serialize an object into a JSON. Sending a `null` value to `App Search` is not possible. Elasticsearch, that is the engine used by App Search, does not to index or search a `null` value, you need to use a special [null_value](https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html) parameter.
We do not recommend to store field without a value.It's better to remove the empty field when you index your data so you can leverage the [exists](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html) query matches of Elasticsearch.

**Comment by ezimuel** [comment]
@gignonje I'm closing this issue. Let mw know if you want to reopen it, thanks.
