### ISSUE TITLE
putSchema is not available 

### ISSUE THREAD

**Issue by voina026** [elastic/enterprise-search-php#20]
I'm trying to update the schema using the `PutSchema` but the `SchemaUpdateRequest` class is empty and the `PutSchema` is required to use the `SchemaUpdateRequest` as a second paramater. 

So there is no way that you can update the schema. Or is there another way?

**Comment by ezimuel** [comment]
@voina026 the `SchemaUpdateRequest` is just an empty POPO class. Similar to [stdClass](https://www.php.net/manual/en/reserved.classes.php) of PHP you can assign any dynamic property that you want, in order to update the schema.
For instance, the example reported [here](https://www.elastic.co/guide/en/app-search/current/schema.html#schema-patch) in the Elastic App Search documentation can be translated in PHP as follows:

```php
use Elastic\EnterpriseSearch\AppSearch\Request;
use Elastic\EnterpriseSearch\AppSearch\Schema;
// ...
$app = $client->appSearch();
$schema = new Schema\SchemaUpdateRequest();
$schema->square_km = "text";

$result = $app->putSchema(
    new Request\PutSchema('national-parks-demo', $schema)
);
```

**Comment by voina026** [comment]
@ezimuel, yes now you mention the solution I can't believe I looked over it. Meanwhile I created a workaround by overruling the class. Thnx!

**Comment by ezimuel** [comment]
@voina026 ok, don't worry. Let me know if you need more help.
