### ISSUE TITLE
Allow Document Creation Without Id

### ISSUE THREAD

**Issue by myleshyson** [elastic/enterprise-search-php#33]
Can the Document class be updated to allow _not_ passing in an id so that elasticsearch can create a unique one on index? 

According to the [documentation](https://www.elastic.co/guide/en/app-search/current/documents.html#documents-create) documents can be created without needing to pass in an id. 

Sometimes you don't have a source for an id and just need elasticsearch to generate a unique one when indexing.

**Comment by ezimuel** [comment]
@myleshyson sorry for the late reply. You right, it's possible to create a document without an `id`. Unfortunately, the specification that we used to generate the `enterprise-search-php` client specify the `id` as required parameter. I'm checking if we can fix the spec, I'll update asap. Thanks for your patience.

**Comment by ezimuel** [comment]
@myleshyson sorry for the late reply,  I figure out a workaround for using documents without `id`. You can use a standard PHP class [stdClass](https://www.php.net/manual/en/class.stdclass.php) instead of `Elastic\EnterpriseSearch\AppSearch\Schema\Document` without the `id` property. This should work just fine.
We are trying to find a better design for the specification since there are cases where `Document` class is needed with the `id` and case where it's not required, as the one that you mentioned.

**Comment by myleshyson** [comment]
Awesome thanks! I feel dumb for not thinking of just using a stdClass 😅 . I'll just use that for now until the Document specification is updated.

**Comment by ezimuel** [comment]
Fixed in version [8.9.0](https://github.com/elastic/enterprise-search-php/releases/tag/v8.9.0)
